[project]
name = "lworth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "angelo-rbs", email = "angeloraphael1@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.pyright]
venvPath = "."
venv = ".venv"
